import React from 'react';
import { usePDF } from 'react-to-pdf';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { TripData, ItineraryDay } from '../pages/Index';

interface ItineraryPDFProps {
  tripData: TripData;
  itinerary: ItineraryDay[];
}

const ItineraryPDF: React.FC<ItineraryPDFProps> = ({ tripData, itinerary }) => {
  const { toPDF, targetRef } = usePDF({
    filename: `trip-itinerary-${tripData.destination}.pdf`,
    page: { format: 'a4', orientation: 'portrait' }
  });

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return (
    <div>
      <Button
        onClick={() => toPDF()}
        className="bg-gradient-to-r from-sky-500 to-coral-500 hover:from-sky-600 hover:to-coral-600"
      >
        <Download className="w-4 h-4 mr-2" />
        Export PDF
      </Button>
      <div style={{ position: 'absolute', left: '-9999px', top: 0 }} aria-hidden="true">
        <div ref={targetRef} className="p-8 max-w-[800px] mx-auto">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-sky-600 mb-2">
              Trip Itinerary: {tripData.destination}
            </h1>
            <p className="text-slate-600">
              {formatDate(tripData.startDate)} - {formatDate(tripData.endDate)}
            </p>
          </div>

          <div className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-4">Trip Details</h2>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-slate-600">Destination</p>
                <p className="font-medium">{tripData.destination}</p>
              </div>
              <div>
                <p className="text-slate-600">Travel Style</p>
                <p className="font-medium capitalize">{tripData.travelStyle}</p>
              </div>
              <div>
                <p className="text-slate-600">Interests</p>
                <p className="font-medium capitalize">
                  {tripData.interests.join(', ')}
                </p>
              </div>
              <div>
                <p className="text-slate-600">Duration</p>
                <p className="font-medium">{tripData.days} days</p>
              </div>
            </div>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-slate-800 mb-4">Daily Schedule</h2>
            {itinerary.map((day) => (
              <div key={day.day} className="mb-6 border-b border-slate-200 pb-6">
                <h3 className="text-lg font-semibold text-sky-600 mb-3">
                  Day {day.day} - {formatDate(day.date)}
                </h3>
                <div className="space-y-4">
                  {day.activities.map((activity) => (
                    <div key={activity.id} className="bg-slate-50 p-4 rounded-lg">
                      <div className="flex justify-between items-start">
                        <div>
                          <h4 className="font-medium text-slate-800">{activity.name}</h4>
                          <p className="text-sm text-slate-600">{activity.description}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-sm font-medium text-sky-600">{activity.time}</p>
                          <p className="text-sm text-slate-500">{activity.duration}</p>
                        </div>
                      </div>
                      <div className="mt-2 flex flex-wrap gap-2">
                        {activity.tags.map((tag) => (
                          <span
                            key={tag}
                            className="text-xs px-2 py-1 bg-sky-100 text-sky-700 rounded-full"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-8 text-center text-sm text-slate-500">
            <p>Generated by PlanMyTrip</p>
            <p>© {new Date().getFullYear()} All rights reserved</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ItineraryPDF; 